# ----------------------------------------------------------------------------------------
#
# Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com)..
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# ----------------------------------------------------------------------------------------

apiVersion: v1
appVersion: "4.3.0"
description: A Helm chart for the deployment of WSO2 Streaming Integrator
name: si
version: 4.3.0-0
icon: https://wso2.cachefly.net/wso2/sites/all/images/wso2logo.svg